name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: |
          npm install --save canvas
          npm install

      - name: Run tests
        run: |
          gulp generic
          gulp generic-es5

      - name: Push changes
        uses: ptienchuan/deploy-github-pages-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: "build"
          target-branch: "gh-pages"
          user-name: "deploy[bot]"
          user-email: "deploy[bot]@noreply.github.com"
